HL minor fixes
turtlebot/turtlebot4-user-manual pull request #5
Opened 2023-03-24 17:06 UTC by hilary-luo

## Description

Minor changes to fix broken links, update install instructions and add some helpful notes.

## How Has This Been Tested?

Built and run as per the readme instructions.

2023-03-28 18:23 UTC, roni-kreinin commented on README.md
> +Update the `_includes` folder locally to match [the Jekyll RTD Theme](https://github.com/rundocs/jekyll-rtd-theme/tree/develop/_includes) without overwriting any existing files.
Did this fix the issues for you? I had to clone the whole rtd-theme repo into the gem bundle to fix it.

2023-03-28 23:58 UTC, hilary-luo commented on README.md
> +Update the `_includes` folder locally to match [the Jekyll RTD Theme](https://github.com/rundocs/jekyll-rtd-theme/tree/develop/_includes) without overwriting any existing files.
Interesting. Yah, this is all I had to do for it to make successfully. I repeated the process in a clean 22.04 VM too to make sure that I could follow this procedure step by step. That being said, I don't really have an opinion about which approach is better, they both work.

2023-03-29 19:17 UTC, roni-kreinin commented on README.md
> +Update the `_includes` folder locally to match [the Jekyll RTD Theme](https://github.com/rundocs/jekyll-rtd-theme/tree/develop/_includes) without overwriting any existing files.
Can you add the required files from rtd-theme to this PR? That way we can just skip this step.

2023-04-05 17:54 UTC, hilary-luo commented on README.md
> +Update the `_includes` folder locally to match [the Jekyll RTD Theme](https://github.com/rundocs/jekyll-rtd-theme/tree/develop/_includes) without overwriting any existing files.
Done and modified the instructions

2023-04-05 18:10 UTC, roni-kreinin requested changes

2023-04-05 18:10 UTC, roni-kreinin commented on software/overview.md
>  There are 2 main computers that run software used by TurtleBot 4: the onboard Raspberry Pi 4, the Create® 3 onboard processor. The user can also connect to the robot with their own PC to visualise se
Replace "Each computer is required to run Ubuntu 20.04 with ROS 2 Galactic." with "Each computer is required to run the same version of Ubuntu and ROS 2 as the TurtleBot 4".

2023-04-05 18:10 UTC, roni-kreinin commented on troubleshooting/faq.md
> +First, check that the Create® 3 is connected to your WiFi network. You should be able to access the Create® 3 portal by entering the Create® 3 IP address in a browser. For information on how to conne
Change "quick start guide" to "Wi-Fi Setup guide"

2023-04-05 18:10 UTC, roni-kreinin commented on tutorials/driving.md
> +The Create® 3 provides a set of [ROS 2 Actions](https://docs.ros.org/en/galactic/Tutorials/Beginner-CLI-Tools/Understanding-ROS2-Actions/Understanding-ROS2-Actions.html) for driving the robot. You ca
Use the Humble link for ROS 2 Actions

2023-04-05 19:54 UTC, hilary-luo commented on tutorials/driving.md
> +The Create® 3 provides a set of [ROS 2 Actions](https://docs.ros.org/en/galactic/Tutorials/Beginner-CLI-Tools/Understanding-ROS2-Actions/Understanding-ROS2-Actions.html) for driving the robot. You ca
Done

2023-04-05 19:54 UTC, hilary-luo commented on troubleshooting/faq.md
> +First, check that the Create® 3 is connected to your WiFi network. You should be able to access the Create® 3 portal by entering the Create® 3 IP address in a browser. For information on how to conne
Done

2023-04-05 19:55 UTC, hilary-luo commented on software/overview.md
>  There are 2 main computers that run software used by TurtleBot 4: the onboard Raspberry Pi 4, the Create® 3 onboard processor. The user can also connect to the robot with their own PC to visualise se
Done

2023-04-05 20:15 UTC, merged